server:
  port: 8085
spring:
  application:
    name: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/vanduy
          jwk-set-uri: http://localhost:9999/realms/vanduy/protocol/openid-connect/certs
  data:
    mongodb:
      uri: mongodb://root:123@localhost:27017/notification-service?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
email:
  dangvanduy4103@gmail.com
password:
  ucmj bdkb hsmw traw
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0