
server:
  port: 8081
spring:
  application:
    name: identity-service

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
        register-with-eureka: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/vanduy
          jwk-set-uri: http://localhost:9999/realms/vanduy/protocol/openid-connect/certs
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
management:
  tracing:
    sampling:
      probability: 1.0

keycloak:
  realm: vanduy
  domain: localhost:9999
  adminClientId: book-store
  adminClientSecret: PyIlQu612larRlBk6mza0sq2llyYMNXN
  username: admin
  password: admin
  urls:
    auth: http://${keycloak.domain}