services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql_container
    environment:
      - MYSQL_DATABASE=BookStoreDB
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    container_name: keycloak_container
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: 123
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
    ports:
      - '9999:8080'
    depends_on:
      - mysql
    networks:
      - keycloak-and-mysql-network

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mysql-data:

networks:
  keycloak-and-mysql-network: