server:
  port: 8084
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/payment_service
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/vanduy
          jwk-set-uri: http://localhost:9999/realms/vanduy/protocol/openid-connect/certs

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: LDH5TS0P
    secretKey: XSPWIB2CAC4E6JIWYQH71DR4FFRYFDCO
    returnUrl: http://localhost:8084/payments/vnpay-return
    version: 2.1.0
    command: pay
    orderType: other
  stripe:
    publicKey: pk_test_51QqcPNAXQYkmBX23KyLVIZcWMOLGr2WPM93NrKAQpcrGAVyYRw8FWqcKIqjIZ4Ey7AxxS8aHeev5ShzT7aUj4fvB007Z5k49wd
    secretKey: sk_test_51QqcPNAXQYkmBX23sdgeULlqzXX7Wyr8gxSQTi1sdShPZbU9pFeDOjtoKjDd7n89tJdBEDGEHFOSGZ9mUvwfpvrp001XR2VanV
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0

